services:
  backend:
    container_name: miniapps_backend
    image: sergeyshelehov/miniapps_backend:latest
    ports:
      - "5176:5176"
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=MiniApp;Username=postgres;Password=1618"
      ConnectionStrings__Redis: "redis:6379"
    depends_on:
      - redis
      - postgres
    networks:
      - miniapps_net

  redis:
    image: redis:latest
    container_name: miniapps_redis
    ports:
      - "6379:6379"
    networks:
      - miniapps_net

  postgres:
    image: postgres:15
    container_name: miniapps_postgres
    restart: always
    environment:
      POSTGRES_DB: MiniApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1618
    ports:
      - "5432:5432"
    networks:
      - miniapps_net

  nginx:
    image: nginx:alpine
    container_name: miniapps_nginx
    ports:
      - "443:443"  
    volumes:
    - ~/nginx.conf:/etc/nginx/nginx.conf
    - /etc/nginx/ssl/server.crt:/etc/ssl/certs/server.crt:ro
    - /etc/nginx/ssl/server.key:/etc/ssl/certs/server.key:ro
    depends_on:
      - backend
    networks:
      - miniapps_net

networks:
  miniapps_net:
    driver: bridge
